language: python
python:
- '3.6'
services: docker

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: mfUN9slcBuQ+6gCCvztpFmN2vtN6t7my9Ffp+4ZDmgdPs7U24N6a6vrZ2sfLdxWCxyidD1cfJmoBxYpSLAp5YTjZefkqs/og8QdEomiQSWnrnwoA0AYPOfN6iPtL6uMt+42NX89UcWtr13pD5JW4q28dlTDzWHwWKAYJj0TLDbrC1kY5SZO18wEmbrz8jjSElcANhf2XwDTa4ehb79RBlLYL/JjOOuyw0Q1IjwGpIB10y/QCRAni/0dp1W7uTV2BBOm2lWBohZF/YxpXIPdcrYImKQvGEOH6r3JvKUhtncyVYdg1VbN85l2VoI5DLSith3uWJvspxc/yZZqIDYsDY/CktszO4Tf+P3czvvjzZ1V687z7UIKM0Y9W9Tk8Pi9ncoBacYP+gkoL2V7li8tKIUxGVdlvK76n9k4pwxqVQwfVra7Zap816hlE1Kd2t3OfBVsJ3QDKaHm5R9tSLInj5IPfWFF9AQgSZxDWeqIJpnMd0qG8wwZ+2p1gyXTgFvCOfnwRZxBIWnyMoQLx9U4XLCkPyd97auoeZlEK5N2jIQBRb3kFh0LbPOB3v4CsBCvMOs0Y4LsHYw9S1N+pa/PyvB+d/QTp/hCnZ2j8PY7axwRV6q0Limp9SWpkkHj2gxkWqsF2wTUbcpGGGZNVvefwPLlL5anSTYeTBMr1O50rLfM=
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .
script: true

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: qSxJthNxCQZywSEr3E1MZGm/dqO5JHVBFQ7E1iNT9+kN5Vue3btZc6CeBER+/y1ne0IWqXv7oH2mayoZHsZK96eo/JNkMhhL1lUoK1N2hVhOgDbd8iauOZDaLvzsj89efvnE4n1+sJnWd1rez1wmNvy1C2fgwQokBjpYWa1k2pCsWcA3+Fjp4+fEmB23WtNF12KYtNXHbOjj+m++PPheLoMV6booDDzCrhHCTdZlGqz2wMe71KEdHNoJL01+AZPY2XkVcjHFnz9oD27D4vcMYz5L9b9IHTciN0qF4NIRM4Uw9fwkevXV7y3SPmlpSkdDTRQW/kiUyISv1+3oxIjaCVLog7aiKg7CLXKCnkdTyAQ0ktvw1Fr+/KoqxOkScUbfleprNxSCqeuAQHvKx31T6NicIqOOOQilYqErJsa7V8FN6+1Fs+TmmVwKk05MHqFvuEtr/XSP5OvyNGe1UR3Mqh+z7cRhcYygNGz4H48Jfz3NxBXghjfuvKCMIl6oFXTHImGNmp1UpTEdXiDlbuyTwsEGabPEskTln78cxkBRHCVwcVk7KYC0n1JYzGMlFUgIHI0mQ0ojQ6VvuCIDnlminsVU/FLFZphPfercN+sQLoEmWlV/n44goTqNCCAI1Bj8Gr1Sxi46Ym7lqJLNnYtpYYsOlEOS41EFxYvVsD0jVQI=
  skip_cleanup: true
  on:
    tags: true
